travelers/urls.py
#coding: utf-8
from __future__ import unicode_literals
from django.conf.urls import patterns, include, url
from . import views

urlpatterns = patterns('travelers.views.sight',
    url(r'^sight/(?P<pk>\d+)/$', 'sight', name='Sight'),
)

urlpatterns += patterns('travelers.views.trace',
    url(r'^city/(?P<city_slug>[-_\w]+)/traces/$', 'city_traces', name='CityTraces'),
)

urlpatterns += patterns('travelers.views.travel',
    url(r'^travels/$', 'all_travels', name='Travels'),
    url(r'^travels/(?P<travel_slug>[-_\w]+)/map/$', 'travel_map', name='TravelMap'),
)

urlpatterns += patterns('travelers.views.traveller',
    url(r'^travelers/$', 'all_travelers', name='Travelers'),
)

urlpatterns += patterns('travelers.views.blog',
    url(r'^blog/$', 'main_blog', name='MainBlog'),
    url(r'^travels/(?P<travel_slug>[-_\w]+)/blog/$', 'travel_blog', name='TravelBlog'),
)

urlpatterns += patterns('travelers.views.city',
    url(r'^$', 'cities', name='Home'),
    url(r'^map/$', 'main_map', name='MainMap'),
    url(r'^city/(?P<city_slug>[-_\w]+)/main/$', 'selected_city', name='MainCity'),
    url(r'^city/(?P<city_slug>[-_\w]+)/map/$', 'city_map', name='CityMap'),
    url(r'^city/(?P<city_slug>[-_\w]+)/sights/$', 'city_sights', name='CitySights'),
    url(r'^cities/$', 'cities', name='Cities'),
    url(r'^region/(?P<pk>\d+)/$', 'region', name='Region'),
)

urlpatterns += patterns('travelers.views.region',
    url(r'^travelers/$', 'all_regions', name='Regions'),
)

urlpatterns += patterns('travelers.views.auth',
    url(r'^logout/$', 'logout'),
)

travelers/models.py
#coding: utf-8
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User


class Sourse(models.Model):
    link = models.CharField('Ссылка', max_length=255, default='', blank=False, unique=True, db_index=True)

    class Meta:
        verbose_name = 'Источник'
        verbose_name_plural = 'Источники'


class TypeOfSights (models.Model):
    title = models.CharField('Название', max_length=255, default='', blank=False)
    time = models.CharField('Время', max_length=100, default='', blank=True)
    colour = models.CharField('Цвет', max_length=30, default='#0000FF', blank=False)
    marker = models.CharField('Маркер', max_length=30, default='marks/flag-export.png', blank=False)

    class Meta:
        verbose_name = 'Тип достопримечательности'
        verbose_name_plural = 'Типы достопримечательностей'


class SectionOfSights(models.Model):
    title = models.CharField('Название', max_length=255, default='', blank=False)
    types = models.ManyToManyField(TypeOfSights, verbose_name='Типы', blank=True, null=True)

    class Meta:
        verbose_name = 'Раздел достопримечательностей'
        verbose_name_plural = 'Разделы достопримечательностей'


class Region(models.Model):
    title = models.CharField('Название', max_length=255, default='', blank=False)
    description = models.TextField('Описание', default='', blank=True)

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name = 'Регион'
        verbose_name_plural = 'Регионы'
        ordering = ('title', )


class CityManager(models.Manager):
    def posted(self):
        return self.filter(posted=True)


class City(models.Model):
    title = models.CharField('Название', max_length=255, default='', blank=False)
    description = models.TextField('Описание', default='', blank=True)
    slug = models.SlugField('Адрес', max_length=255, blank=False, db_index=True)
    default_zoom = models.PositiveSmallIntegerField('Масштаб', blank=True, default=0)
    centre_coordinates = models.CharField('Координаты', max_length=100, default='', blank=True)
    posted = models.BooleanField('Опубликовано', default=False)
    show_on_mainmap = models.BooleanField('Показывать на гавной карте', default=False)
    regional_center = models.BooleanField('Региональный центр', default=True)
    region = models.ForeignKey(Region, verbose_name='Регион', null=True, blank=False, default=None)
    add_date = models.DateTimeField('Дата добавления', null=True, blank=False, auto_now_add=True)
    last_modified_date = models.DateTimeField('Дата последнего изменения', null=True, blank=False, auto_now=True)
    autotravel_url = models.CharField('URL', max_length=255, default='', blank=True)

    objects = CityManager()

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name = 'Город'
        verbose_name_plural = 'Города'
        ordering = ('title', 'slug')


class Sight (models.Model):
    title = models.CharField('Название', max_length=255, default='', blank=False)
    text = models.TextField('Описание', default='', blank=False)
    original_coordinates = models.CharField('Стянутные координаты', max_length=100, default='', blank=True)
    coordinates = models.CharField('Координаты', max_length=100, default='', blank=True)
    posted = models.BooleanField('Опубликовано', default=False)
    type = models.ManyToManyField(TypeOfSights, verbose_name='Достопримечательности', blank=False, null=False)
    city = models.ForeignKey(City, verbose_name='Город', blank=True, null=True)
    regional = models.BooleanField('В регионе', default=False)
    price = models.CharField('Цена', max_length=100, null=True, blank=True)
    add_date = models.DateTimeField('Дата добавления', null=True, blank=False, auto_now_add=True)
    fix_date = models.DateTimeField('Дата исправления', null=True, blank=False, auto_now=True)
    address = models.CharField('Адрес', max_length=255, default='', blank=True)
    autotravel_url = models.CharField('URL', max_length=255, default='', blank=True)

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name = 'Достопримечательность'
        verbose_name_plural = 'Достопримечтельности'


class Traveler(models.Model):
    name = models.CharField('Имя', max_length=255, default='', blank=False)
    link = models.CharField('Ссылка', max_length=255, default='', blank=True, unique=True)
    photo = models.CharField('Фото', max_length=255, default='http://gpsnew.ru/images/products/no_picture.jpg', blank=False)
    sourses = models.ManyToManyField(Sourse, verbose_name='Источники', blank=False, null=False)

    class Meta:
        verbose_name = 'Путешественник'
        verbose_name_plural = 'Путешественники'


class Post(models.Model):
    title = models.CharField('Заголовок', max_length=255, default='', blank=True)
    link = models.CharField('Ссылка', max_length=255, default='', blank=True, db_index=True)
    text = models.TextField('Текст', default='', blank=False)
    coordinates = models.CharField('Координаты', max_length=100, default='', blank=True)
    posted = models.BooleanField('Опубликовано', default=False)
    sight = models.ForeignKey(Sight, verbose_name='Достопримечательность', blank=True, null=True)

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'


class PostPhoto(models.Model):
    file = models.ImageField('Изображение', default='', blank=False, upload_to='images/photo/')
    posts = models.ForeignKey(Post, verbose_name='Сообщения', blank=False, null=False)

    class Meta:
        verbose_name = 'Фотография отзыва'
        verbose_name_plural = 'Фотографии отзыва'


class Tag(models.Model):
    tag = models.CharField('Тэг', max_length="50", default='', blank=False, null=False)
    post = models.ManyToManyField(Post, verbose_name='Запись', blank=False, null=False)

    class Meta:
        verbose_name = 'Тэг'
        verbose_name_plural = 'Тэги'


class SighPhoto(models.Model):
    file = models.ImageField('Изображение', default='', blank=False, upload_to='images/photo/')
    sight = models.ForeignKey(Sight, verbose_name='Достпримечательность', blank=False, null=True)
    posted = models.BooleanField('Опубликовано', default=True)

    class Meta:
        verbose_name = 'Фотография достопримечательности'
        verbose_name_plural = 'Фотографии достопримечательности'
        unique_together = ('file', 'sight')


class Travel(models.Model):
    title = models.CharField('Название', max_length=255, default='', blank=False)
    slug = models.SlugField('Адрес', max_length=255, blank=False, db_index=True)
    tag = models.CharField('Тэг', max_length=255, default='', blank=True)
    travelers = models.ManyToManyField(Traveler, verbose_name='Путешественники', blank=False, null=False)
    sourses = models.ManyToManyField(Sourse, verbose_name='Источники', blank=False, null=False)
    photo = models.CharField('Фото', max_length=255, default='', blank=False)
    city = models.CharField('Город', max_length=255, default='', blank=False)

    class Meta:
        verbose_name = 'Путешествие'
        verbose_name_plural = 'Путешествия'


class Route(models.Model):
    places = models.ManyToManyField(Sight, verbose_name='Места', blank=False, null=False)
    user = models.ForeignKey(User, verbose_name='Пользователь', blank=True, null=True)
    posted = models.BooleanField('Опубликовано', default=False)
    city = models.ForeignKey(City, verbose_name='Город', blank=False, null=False)

    class Meta:
        verbose_name = 'Маршрут'
        verbose_name_plural = 'Маршруты'


class PopularPlace(models.Model):
    sight = models.ForeignKey(Sight, verbose_name='Популярные места', blank=False, default='')
    time_with = models.DateTimeField('Время с', auto_now_add=True, )
    time_to = models.DateTimeField('Время до', auto_now_add=True, )

    class Meta:
        verbose_name = 'Популярное место'
        verbose_name_plural = 'Популярные места'


class PopularTraces(models.Model):
    sight = models.ForeignKey(Sight, verbose_name='Популярные места', blank=False, default='')
    time_with = models.DateTimeField('Время с', auto_now_add=True,  )
    time_to = models.DateTimeField('Время до', auto_now_add=True, )

    class Meta:
        verbose_name = 'Популярный маршрут'
        verbose_name_plural = 'Попуялрные маршруты'

travelers/views/blog.py
# coding: utf-8
from __future__ import unicode_literals
from django.views.generic import ListView
from travelers.views.mixins import PostedMixin, TravelMixin
from travelers.models import Post


class MainBlog(PostedMixin, ListView):
    model = Post
    template_name = 'mainblog.html'
    context_object_name = 'travel_reviews'
main_blog = MainBlog.as_view()


class TravelBlog(TravelMixin, MainBlog):
    template_name = 'travelblog.html'
travel_blog = TravelBlog.as_view()

travelers/views/city.py
# coding: utf-8
from __future__ import unicode_literals
from django.views.generic import ListView, DetailView
from travelers.views.mixins import PostedMixin, CityMixin
from travelers.models import City, Sight, Region


class Map(PostedMixin, ListView):
    template_name = 'mainmap.html'
    model = Sight
    context_object_name = 'sights'
main_map = Map.as_view()


class CityMap(CityMixin, Map):
    template_name = 'citymap.html'

    def get_queryset(self):
        return super(CityMap, self).get_queryset().exclude(coordinates='')
city_map = CityMap.as_view()


class SelectedCity(DetailView):
    template_name = 'city.html'
    model = City
    context_object_name = 'city'
    slug_url_kwarg = 'city_slug'
selected_city = SelectedCity.as_view()


class CitySights(CityMap):
    template_name = 'CitySights.html'
city_sights = CitySights.as_view()


class MainCity(PostedMixin, ListView):
    template_name = 'cities.html'
    model = City
    context_object_name = 'cities'

    def get_queryset(self):
        return super(MainCity, self).get_queryset().filter(show_on_mainmap=True)
cities = MainCity.as_view()


class RegionalMap(DetailView):
    template_name = 'region.html'
    model = Region
    context_object_name = 'region'
region = RegionalMap.as_view()

travelers/views/mixins.py
# coding: utf-8
from __future__ import unicode_literals
from travelers.models import City


class PostedMixin(object):
    def get_queryset(self):
        return super(PostedMixin, self).get_queryset().filter(posted=True)


class TravelMixin(object):
    template_context_name = 'travel_posts'

    def get_queryset(self):
        return super(TravelMixin, self).get_queryset().filter(slug=self.kwargs['travel_slug'])


class CityMixin(object):
    template_context_name = 'travel_posts'

    def get_queryset(self):
        return super(CityMixin, self).get_queryset().filter(city__slug=self.kwargs['city_slug'])

    def get_context_data(self, **kwargs):
        context = super(CityMixin, self).get_context_data(**kwargs)
        context['selected_city'] = City.objects.get(slug=self.kwargs['city_slug'])
        return context

travelers/views/region.py
# coding: utf-8
from __future__ import unicode_literals
from django.views.generic import ListView
from travelers.models import Region


class AllRegions(ListView):
    model = Region
all_regions = AllRegions.as_view()

travelers/views/sight.py
# coding: utf-8
from __future__ import unicode_literals
from django.views.generic import DetailView
from travelers.models import Sight


class SightView(DetailView):
    template_name = 'sight.html'
    model = Sight
    context_object_name = 'sight'
sight = SightView.as_view()

travelers/views/trace.py
# coding: utf-8
from __future__ import unicode_literals
from django.views.generic import ListView
from travelers.models import Route
from travelers.views.mixins import CityMixin


class CityTraces(CityMixin, ListView):
    template_name = 'maintraces.html'
    model = Route
    context_object_name = 'traces'
city_traces = CityTraces.as_view()

travelers/views/travel.py
# coding: utf-8
from __future__ import unicode_literals
from django.views.generic import ListView
from travelers.models import Travel, Post
from travelers.views.mixins import TravelMixin


class AllTravels(ListView):
    model = Travel
    template_name = 'maintravels.html'
    context_object_name = 'travels'
all_travels = AllTravels.as_view()


class TravelMap(TravelMixin, ListView):
    model = Post
travel_map = TravelMap.as_view()

travelers/views/traveller.py
# coding: utf-8
from __future__ import unicode_literals
from django.views.generic import ListView
from travelers.models import Traveler


class AllTravelers(ListView):
    model = Traveler
    template_name = 'maintravelers.html'
    context_object_name = 'travelers'
all_travelers = AllTravelers.as_view()

travelers/templates/CitySights.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block main_menu %}
{% include "includes/city_menu.html" %}
{% endblock main_menu %}
{% block content %}
    <div class="row">
    {% for sight in sights %}
        <div class="col-md-3">
    <div class="thumbnail">
        <div class="caption">
            <h5>{{ sight.title }}</h5>
{#        <p>{{  sight.sighphoto_set.first.file.url }}</p>#}
            {% thumbnail sight.sighphoto_set.first.file "300x200" crop="center" as image %}
            <img src="{{ image.url }}">
            {% empty %}
            <img src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMDAiIGhlaWdodD0iMjAwIj48cmVjdCB3aWR0aD0iMzAwIiBoZWlnaHQ9IjIwMCIgZmlsbD0iI2VlZSIvPjx0ZXh0IHRleHQtYW5jaG9yPSJtaWRkbGUiIHg9IjE1MCIgeT0iMTAwIiBzdHlsZT0iZmlsbDojYWFhO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1zaXplOjE5cHg7Zm9udC1mYW1pbHk6QXJpYWwsSGVsdmV0aWNhLHNhbnMtc2VyaWY7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+MzAweDIwMDwvdGV4dD48L3N2Zz4=">
            {% endthumbnail %}
            <div class="sight-link">
                <i class="glyphicon glyphicon-map-marker"></i>
                <a href="{% url 'Sight' sight.pk %}">Показать на карте</a>
            </div>
            <p>{{ sight.text|truncatechars:133 }}</p> <a href="{% url 'Sight' sight.pk %}"> -подробнее...- </a>
        </div>
    </div>
        </div>
    {% endfor %}
    </div>
{% endblock content %}

travelers/templates/base.html
{% load staticfiles %}
{% load city_tags %}
{% load travelers_menu %}
<!DOCTYPE html>
<html>
    <head lang="en">
        <meta charset="UTF-8">
        {% block ymap %}{% endblock ymap%}
        <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
        <link href="{% static 'style.css' %}" rel="stylesheet">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/my_scripts.js' %}"></script>
        <script src="{% static 'js/scripts.js' %}"></script>
        <title>{% block title %}{% endblock title %} - russiantravel - {% block extended_title %}Все достопримечательности России{% endblock extended_title %}</title>
    </head>
    <body>
    <!-- Yandex.Metrika counter -->
        <script type="text/javascript">
            (function (d, w, c) {
                (w[c] = w[c] || []).push(function() {
                    try {
                        w.yaCounter41665104 = new Ya.Metrika({
                            id:41665104,
                            clickmap:true,
                            trackLinks:true,
                            accurateTrackBounce:true
                        });
                    } catch(e) { }
                });

                var n = d.getElementsByTagName("script")[0],
                    s = d.createElement("script"),
                    f = function () { n.parentNode.insertBefore(s, n); };
                s.type = "text/javascript";
                s.async = true;
                s.src = "https://mc.yandex.ru/metrika/watch.js";

                if (w.opera == "[object Opera]") {
                    d.addEventListener("DOMContentLoaded", f, false);
                } else { f(); }
            })(document, window, "yandex_metrika_callbacks");
        </script>
        <noscript><div><img src="https://mc.yandex.ru/watch/41665104" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
    <!-- /Yandex.Metrika counter -->
        <nav class="navbar navbar-default navbar-fixed-top menu" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a href="/" class="navbar-brand">RUSSIANTRAVEL</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        {% block main_menu %}
                        <li {% if request.path == '/' %}class="active" {% endif %}><a href="{% url 'Home' %}">-ВСЕ ГОРОДА-</a></li>
{#                        <li {% if request.path == '/blog/' %}class="active" {% endif %}><a href="{% url 'MainBlog' %}">-ОБЩИЙ БЛОГ-</a></li>#}
{#                        <li {% if request.path == '/travels/' %}class="active" {% endif %}><a href="{% url 'Travels' %}">-ПУТЕШЕСТВИЯ-</a></li>#}
{#                        <li {% if request.path == '/travelers/' %}class="active" {% endif %}><a href="{% url 'Travelers' %}">-ПУТЕШЕСТВЕННИКИ-</a></li>#}
{#                        <li><a href="#">-ПОПУЛЯРНОЕ-</a></li>#}
{#                        <li><a href="#">-СОТРУДНИЧЕСТВО-</a></li>#}
{#                        <li style="margin-left: 125px;"><input type="text" class="form-control" id="search" value="Поиск..."><i class="glyphicon glyphicon-search"></i></li>#}
                        {% endblock main_menu %}
                    </ul>
                </div>
            </div>
        </nav>
        {% comment %}
        <nav class="navbar navbar-default navbar-fixed-top sort">
            <div class="container-fluid">
                <div class="collapse navbar-collapse">
                    <div class="budget">
                        <p class="navbar-text">БЮДЖЕТ:</p>
                        <div class="btn-group">
                            <a class="dropdown-toggle my-dropdown-menu" id="main1" data-toggle="dropdown">500-1000 P</a>
                            <span class="caret"></span>
                            <ul class="dropdown-menu" id="menu1">
                                <li><a href="#" id="value1">500-1000 P</a></li>
                                <li><a href="#" id="value2">2</a></li>
                                <li><a href="#" id="value3">3</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="with-who">
                        <p class="navbar-text">C КЕМ:</p>
                        <div class="btn-group">
                            <a class="dropdown-toggle my-dropdown-menu" id="main2" data-toggle="dropdown">С ДРУЗЬЯМИ</a>
                            <span class="caret"></span>
                            <ul class="dropdown-menu" id="menu2">
                                <li><a href="#" id="value1">С ДРУЗЬЯМИ</a></li>
                                <li><a href="#" id="value2">2</a></li>
                                <li><a href="#" id="value3">3</a></li>
                             </ul>
                        </div>
                    </div>
                    <div class="category">
                        <p class="navbar-text">КАТЕГОРИЯ:</p>
                        <div class="btn-group">
                            <a class="dropdown-toggle my-dropdown-menu" id="main3" data-toggle="dropdown">ДОСТОПРИМЕЧАТЕЛЬНОСТИ</a>
                            <span class="caret"></span>
                            <ul class="dropdown-menu" id="menu3">
                                <li><a href="#" id="value1">ДОСТОПРИМЕЧАТЕЛЬНОСТИ</a></li>
                                <li><a href="#" id="value2">2</a></li>
                                <li><a href="#" id="value3">3</a></li>
                             </ul>
                        </div>
                    </div>
                    <button type="button" class="btn btn-info success">OK</button>
                </div>
            </div>
        </nav>
        <nav class="navbar navbar-default navbar-fixed-top auth">
            <div class="container-fluid">
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li>Выбрать город</li>
                        <li class="change-city">
                            <div class="btn-group">
                                <a class="dropdown-toggle my-dropdown-menu" id="main1" data-toggle="dropdown">{% current_city %}</a>
                                <span class="caret"></span>
                                <ul class="dropdown-menu" id="menu4">
                                    {% city_chooser %}
                                </ul>
                            </div>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right auth-text">
                        {% if request.user.is_authenticated %}<li>Вы вошли как: {{ request.user.get_full_name }}</li>
                        <li><a id="btn2" class="logout-btn" rel="reg_form" href="/logout">Выход</a></li>
                        {% else %}
                                <a class="show_popup" rel="reg_form" href="#" id="btn" onclick="change();">Вход через соц.сети</a>
                                    <div class="popup reg_form">    <a class="close" href="#">Close</a>
                                        <h2>Вход через соц.сети</h2>
                                        <a href="/login/vk-oauth2" title="Зайти через ВКонтакте"><img src="{% static 'images/vk.jpg' %}" ></a>
                                        <a href="{% url 'social:begin' 'twitter' %}?next={{ request.path }}" title="Зайти через Twitter"><img src="{% static 'images/tw.png' %}" ></a>
                                    </div>
                        {% endif %}

                    </ul>
                </div>
            </div>
        </nav>
        {% endcomment %}
        {% block left_menu %}
        {% cities_menu %}
        {% endblock left_menu %}
        {% block mapCase %}{% endblock mapCase %}
        <div class="content">
        {% block content %}{% endblock content %}
        </div>
    </body>
</html>

travelers/templates/blog.html
{% extends "base.html" %}
{% block content %}{% endblock content %}

travelers/templates/cities.html
{% extends "map.html" %}
{% block title %}Все города{% endblock title %}
{% block add_geo_objects %}

{% for city in cities %}
.add(new ymaps.Placemark([{{ city.centre_coordinates }}], {
        balloonContent: '<a href="{% url 'CityMap' city.slug %}">{{ city.title }}</a>'
    }, {
        preset: 'islands#dotIcon',
        iconColor: '#3b5998'
    }))
{% endfor %}

{% endblock add_geo_objects %}

travelers/templates/mainblog.html
{% extends "blog.html" %}
{% block main_title %}{% endblock main_title %}

travelers/templates/map.html
{% extends "base.html" %}
{% load staticfiles %}
{% load thumbnail %}
{% load city_tags %}
{% block title %}Карта{% endblock title %}
{% block ymap %}
    <link href="{% static 'mapStyle.css' %}" rel="stylesheet">
    <script src="https://api-maps.yandex.ru/2.0-stable/?load=package.full&lang=ru-RU" type="text/javascript" xmlns="http://www.w3.org/1999/html"></script>
    <script>
        ymaps.ready(init);
        var map;
        function init() {
            map = new ymaps.Map("map", {
                {% block center_and_zoom %}
                center: [58.02265172, 56.22863050],
                zoom: 15,
                {% endblock center_and_zoom %}
                behaviors: ['default','scrollZoom']
            }, {
                searchControlProvider: 'yandex#search'
            });
            map.controls.add('zoomControl');
            var collection = new ymaps.GeoObjectCollection();
            collection
                    {% block add_geo_objects %}
                        {% for sight in sights %}
                            .add(new ymaps.Placemark([{{ sight.coordinates }}], {
                                    balloonContentHeader: '{{ sight.title }}',
                                    balloonContentBody: '{% thumbnail sight.sighphoto_set.first.file "300x200" crop="center" as image %} <img src="{{ image.url }}" width="300" height="200">{% endthumbnail %}'
                                }, {
                                    iconLayout: 'default#image',
                                    iconImageHref: '{% static sight.type_of_sights_set.first.marker|default:"/static/marks/flag-export.png" %}',
                                    iconImageSize: [32, 32]
                                }))
                        {% endfor %}
                    {% endblock add_geo_objects %}
        map.geoObjects.add(collection);
        {% block set_bounds %}
        map.setBounds(collection.getBounds());
        {% endblock set_bounds %}
        }
    </script>
{% endblock ymap %}
{% block mapCase %}
    <div id="map"></div>
{% endblock mapCase %}
{% block content %}
    {% block main_title %}
    {% endblock main_title %}
    {% block floating_block %}
    <div class="nav">
        <h1>{% block floating_block_title %} Russiantravel - все достопримечательности России {% endblock floating_block_title %}</h1>
        <p>{% block floating_block_content %} Найдите интересные места в городах, выбрав их на карте или в списке слева {% endblock floating_block_content %}</p>
    </div>
    {% endblock floating_block %}
{% endblock content %}

travelers/templates/region.html
{% extends "map.html" %}
{% load travelers_menu %}
{% block title %}{{ region.title }}{% endblock title %}
{% block add_geo_objects %}

{% for city in region.city_set.posted %}
.add(new ymaps.Placemark([{{ city.centre_coordinates }}], {
        balloonContent: '<a href="{% url 'CityMap' city.slug %}">{{ city.title }}</a>'
    }, {
        preset: 'islands#dotIcon',
        iconColor: '#3b5998'
    }))
{% endfor %}

{% endblock add_geo_objects %}

{% block left_menu %}
    {% region_menu %}
{% endblock left_menu %}


{% block floating_block_title %} {{ region.title }} {% endblock floating_block_title %}
{% block floating_block_content %} {{ region.description }} {% endblock floating_block_content %}

travelers/templates/sight.html
{% extends "map.html" %}
{% load staticfiles %}
{% load thumbnail %}
{% load city_tags %}

{% block title %}{{ sight.title }} - Карта{% endblock title %}

{% block main_menu %}
{% include "includes/sight_menu.html" %}
{% endblock main_menu %}

 {% block add_geo_objects %}
    .add(new ymaps.Placemark([{{ sight.coordinates }}], {
            balloonContentHeader: '{{ sight.title }}',
            balloonContentBody: '{% thumbnail sight.sighphoto_set.first.file "300x200" crop="center" as image %} <img src="{{ image.url }}" width="300" height="200">{% endthumbnail %}'
        }, {
            iconLayout: 'default#image',
            iconImageHref: '{% static "marks/flag-export.png" %}',
            iconImageSize: [32, 32]
        }))
{% endblock add_geo_objects %}

{% block set_bounds %}
{% endblock set_bounds %}

{% block center_and_zoom %}
    center: [{{ sight.coordinates }}],
    zoom: 18,
{% endblock center_and_zoom %}

{% block floating_block_title %} {{ sight.title }} {% endblock floating_block_title %}
{% block floating_block_content %} {{ sight.text }} {% endblock floating_block_content %}